name: audio_py
channels:
  - anaconda
  - defaults
dependencies:
  - astroid=2.6.6
  - blas=1.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - dbus=1.13.18
  - expat=2.2.10
  - gettext=0.19.8.1
  - glib=2.66.1
  - icu=58.2
  - intel-openmp=2020.2
  - isort=5.9.3
  - jpeg=9b
  - lazy-object-proxy=1.6.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1l
  - pcre=8.44
  - pip=21.0.1
  - portaudio=19.6.0
  - pyaudio=0.2.11
  - pylint=2.9.6
  - pyqt=5.9.2
  - pyqtgraph=0.11.0
  - python=3.7.11
  - qt=5.9.7
  - readline=8.1
  - scipy=1.5.2
  - setuptools=58.0.4
  - sip=4.19.24
  - six=1.15.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
